# Generated by Django 6.0.5 on 2026-08-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_brand_medicine_brand_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
