# Generated by Django 6.0.5 on 2026-08-07 08:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_brand_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('parameters_included', models.TextField(blank=True, null=True)),
                ('sample_type', models.CharField(choices=[('BLOOD', 'Blood'), ('URINE', 'Urine'), ('SWAB', 'Swab'), ('OTHER', 'Other')], default='BLOOD', max_length=10)),
                ('fasting_required', models.BooleanField(default=False)),
                ('reporting_time', models.CharField(blank=True, max_length=100, null=True)),
                ('is_package', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('total_bookings', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lab_tests',
            },
        ),
        migrations.CreateModel(
            name='LabTestCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'lab test categories',
                'db_table': 'lab_test_categories',
            },
        ),
        migrations.CreateModel(
            name='LabTestBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField()),
                ('time_slot', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('SAMPLE_COLLECTED', 'Sample Collected'), ('REPORT_READY', 'Report Ready'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('report_url', models.CharField(blank=True, max_length=500, null=True)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_test_bookings', to='api.address')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='api.labtest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_test_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lab_test_bookings',
                'ordering': ['-booked_at'],
            },
        ),
        migrations.AddField(
            model_name='labtest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_tests', to='api.labtestcategory'),
        ),
    ]
