# Generated by Django 6.0.5 on 2026-08-07 09:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_lab_tests'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('cover_image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('author', models.CharField(default='PharmaX Team', max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'blog_posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
