# Generated by Django 6.0.5 on 2026-08-07 09:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_blog_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('frequency_days', models.IntegerField(choices=[(7, 'Weekly'), (15, 'Every 15 Days'), (30, 'Monthly'), (60, 'Every 2 Months'), (90, 'Every 3 Months')], default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('next_delivery_date', models.DateField()),
                ('last_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='api.address')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='api.medicine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'medicine_subscriptions',
                'ordering': ['next_delivery_date'],
            },
        ),
    ]
