# Generated by Django 6.0.5 on 2026-08-08 05:23

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_grandfather_existing_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('BROADCASTING', 'Broadcasting'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('PLACED', 'Placed'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], default='PLACED', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('ADMIN', 'Admin'), ('PHARMACY', 'Pharmacy'), ('DELIVERY_AGENT', 'Delivery Agent')], default='CUSTOMER', max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(blank=True, max_length=50, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_agent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'delivery_agents',
            },
        ),
        migrations.CreateModel(
            name='OrderFulfillment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('BROADCASTING', 'Broadcasting'), ('ACCEPTED', 'Accepted'), ('NO_PHARMACY_FOUND', 'No Pharmacy Found'), ('AWAITING_DELIVERY', 'Awaiting Delivery'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='BROADCASTING', max_length=20)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfillments', to='api.deliveryagent')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='api.order')),
            ],
            options={
                'db_table': 'order_fulfillments',
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fulfillment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='api.orderfulfillment'),
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pharmacies',
            },
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfillments', to='api.pharmacy'),
        ),
        migrations.CreateModel(
            name='FulfillmentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_requests', to='api.orderitem')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_requests', to='api.pharmacy')),
            ],
            options={
                'db_table': 'fulfillment_requests',
                'unique_together': {('order_item', 'pharmacy')},
            },
        ),
        migrations.CreateModel(
            name='PharmacyMedicineListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('expiry_date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_listings', to='api.medicine')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='api.pharmacy')),
            ],
            options={
                'db_table': 'pharmacy_medicine_listings',
                'indexes': [models.Index(fields=['medicine', 'is_available'], name='pharmacy_me_medicin_8a49aa_idx')],
                'unique_together': {('pharmacy', 'medicine')},
            },
        ),
    ]
