# Generated by Django 6.0.5 on 2026-08-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_seed_marketplace_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfulfillment',
            name='delivery_broadcast_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
