# Generated by Django 6.0.5 on 2026-08-08 08:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_orderfulfillment_delivery_broadcast_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAgentCodLiability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_collected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REMITTED', 'Remitted')], default='PENDING', max_length=20)),
                ('remittance_method', models.CharField(blank=True, choices=[('CASH_DEPOSIT', 'Cash Deposit at Office'), ('GATEWAY_TOPUP', 'Gateway Top-up')], max_length=20, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('remitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cod_liabilities', to='api.deliveryagent')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fulfillment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cod_liability', to='api.orderfulfillment')),
            ],
            options={
                'db_table': 'delivery_agent_cod_liabilities',
            },
        ),
        migrations.CreateModel(
            name='DeliveryAgentEarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earnings', to='api.deliveryagent')),
                ('fulfillment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='agent_earning', to='api.orderfulfillment')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'delivery_agent_earnings',
            },
        ),
        migrations.CreateModel(
            name='PharmacyPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_payable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('funding_source', models.CharField(choices=[('ORDER_REVENUE', 'Order Revenue'), ('PLATFORM_FUNDS', 'Platform Funds')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fulfillment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_payout', to='api.orderfulfillment')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='api.pharmacy')),
            ],
            options={
                'db_table': 'pharmacy_payouts',
            },
        ),
    ]
