# Generated by Django 6.0.5 on 2026-08-08 13:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_deliveryagentcodliability_deliveryagentearning_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyTeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='api.pharmacy')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pharmacy_team_members',
            },
        ),
    ]
