# Generated by Django 6.0.5 on 2026-08-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_pharmacy_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyteammember',
            name='can_view_finance',
            field=models.BooleanField(default=False),
        ),
    ]
