# Generated by Django 6.0.5 on 2026-08-08 14:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_pharmacy_team_finance_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='logo_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='PharmacyBusinessHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_closed', models.BooleanField(default=False)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='api.pharmacy')),
            ],
            options={
                'db_table': 'pharmacy_business_hours',
                'ordering': ['weekday'],
                'unique_together': {('pharmacy', 'weekday')},
            },
        ),
    ]
