# Generated by Django 6.0.5 on 2026-08-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_pharmacy_profile_and_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('CART', 'Cart'), ('DIRECT', 'Buy Now')], default='CART', max_length=10),
        ),
    ]
