# Generated by Django 6.0.5 on 2026-08-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_order_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinereminder',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('AS_NEEDED', 'As Needed')], default='DAILY', max_length=20),
        ),
    ]
