# Generated by Django 6.0.5 on 2026-08-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_reminder_monthly_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('BROADCASTING', 'Broadcasting'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('NO_PHARMACY_FOUND', 'No Pharmacy Found'), ('PLACED', 'Placed'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], default='PLACED', max_length=20),
        ),
    ]
