# Generated by Django 6.0.5 on 2026-08-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_pharmacy_compliance_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfulfillment',
            name='status',
            field=models.CharField(choices=[('BROADCASTING', 'Broadcasting'), ('ACCEPTED', 'Accepted'), ('NO_PHARMACY_FOUND', 'No Pharmacy Found'), ('PREPARED', 'Prepared'), ('PACKED', 'Packed'), ('AWAITING_DELIVERY', 'Awaiting Delivery'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='BROADCASTING', max_length=20),
        ),
    ]
