# Generated by Django 6.0.5 on 2026-08-09 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_fulfillment_prep_stages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['id']},
        ),
    ]
