# Generated by Django 6.0.5 on 2026-08-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_pharmacylocationchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfulfillment',
            name='delivery_stale_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
