# Generated by Django 6.0.5 on 2026-08-12 07:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_orderfulfillment_delivery_stale_notified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDecline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declines', to='api.deliveryagent')),
                ('fulfillment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declines', to='api.orderfulfillment')),
            ],
            options={
                'db_table': 'delivery_declines',
                'unique_together': {('agent', 'fulfillment')},
            },
        ),
    ]
