# Generated by Django 6.0.5 on 2026-08-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_deliverydecline'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfulfillment',
            name='rider_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='rider_rating_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
