# Generated by Django 6.0.5 on 2026-08-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_prescription_medicines_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
