# Generated by Django 6.0.5 on 2026-08-15 09:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_prescription_admin_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='prescriptions/')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_files', to='api.prescription')),
            ],
            options={
                'db_table': 'prescription_files',
            },
        ),
    ]
