# Generated by Django 6.0.5 on 2026-08-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_prescriptionfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('AWAITING_PRESCRIPTION', 'Awaiting Prescription Verification'), ('PRESCRIPTION_REJECTED', 'Prescription Rejected'), ('BROADCASTING', 'Broadcasting'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('NO_PHARMACY_FOUND', 'No Pharmacy Found'), ('PLACED', 'Placed'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], default='PLACED', max_length=25),
        ),
    ]
