# Generated by Django 6.0.5 on 2026-08-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfulfillment',
            name='pickup_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='pickup_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
