# Generated by Django 6.0.5 on 2026-08-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_seed_doctor_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='khalti_pidx',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
