# Generated by Django 6.0.5 on 2026-08-23 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_doctorappointment_khalti_pidx'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription', to='api.doctorappointment'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='source',
            field=models.CharField(choices=[('UPLOAD', 'Uploaded by Patient'), ('CONSULTATION', 'Issued by Doctor')], default='UPLOAD', max_length=20),
        ),
        migrations.CreateModel(
            name='PrescriptionLabTestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.labtestbooking')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.labtest')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_test_items', to='api.prescription')),
            ],
            options={
                'db_table': 'prescription_lab_test_items',
            },
        ),
    ]
