# Generated by Django 6.0.5 on 2026-08-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_prescription_appointment_prescription_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='follow_up_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
