# Generated by Django 6.0.5 on 2026-08-23 17:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_doctorappointment_follow_up_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestbooking',
            name='collector_broadcast_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestbooking',
            name='khalti_pidx',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labtestbooking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('KHALTI', 'Khalti'), ('ESEWA', 'eSewa'), ('CASH_ON_DELIVERY', 'Cash on Collection')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='labtestbooking',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='labtestbooking',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='lab_reports/'),
        ),
        migrations.AddField(
            model_name='labtestbooking',
            name='report_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('ADMIN', 'Admin'), ('PHARMACY', 'Pharmacy'), ('DELIVERY_AGENT', 'Delivery Agent'), ('DOCTOR', 'Doctor'), ('LAB_COLLECTOR', 'Lab Collector')], default='CUSTOMER', max_length=20),
        ),
        migrations.CreateModel(
            name='LabCollector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_collector', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lab_collectors',
            },
        ),
        migrations.CreateModel(
            name='CollectorEarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='collector_earning', to='api.labtestbooking')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earnings', to='api.labcollector')),
            ],
            options={
                'db_table': 'collector_earnings',
            },
        ),
        migrations.CreateModel(
            name='CollectorCodLiability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_collected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REMITTED', 'Remitted')], default='PENDING', max_length=20)),
                ('remittance_method', models.CharField(blank=True, choices=[('CASH_DEPOSIT', 'Cash Deposit at Office'), ('GATEWAY_TOPUP', 'Gateway Top-up')], max_length=20, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('remitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cod_liability', to='api.labtestbooking')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cod_liabilities', to='api.labcollector')),
            ],
            options={
                'db_table': 'collector_cod_liabilities',
            },
        ),
        migrations.AddField(
            model_name='labtestbooking',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='api.labcollector'),
        ),
    ]
