# Generated by Django 6.0.5 on 2026-08-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_seed_lab_collector_payout_flat'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestbooking',
            name='esewa_transaction_uuid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
