# Generated by Django 6.0.5 on 2026-08-25 11:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_backfill_free_doctor_consultation_benefit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyIncentiveCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('campaign_type', models.CharField(choices=[('DISCOUNT', 'Reduced Commission'), ('BONUS', 'Cash Bonus')], max_length=20)),
                ('discounted_commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bonus_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pharmacy_incentive_campaigns',
            },
        ),
        migrations.CreateModel(
            name='PharmacyCampaignEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('bonus_paid', models.BooleanField(default=False)),
                ('bonus_paid_at', models.DateTimeField(blank=True, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_enrollments', to='api.pharmacy')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.pharmacyincentivecampaign')),
            ],
            options={
                'db_table': 'pharmacy_campaign_enrollments',
                'unique_together': {('campaign', 'pharmacy')},
            },
        ),
    ]
