# Generated by Django 6.0.5 on 2026-08-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_pharmacyincentivecampaign_pharmacycampaignenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='promobanner',
            name='placement',
            field=models.CharField(choices=[('HERO', 'Hero (top slider)'), ('MID_PAGE', 'Mid-page (after product rail)'), ('PRE_FOOTER', 'Pre-footer (before stats)')], default='HERO', max_length=20),
        ),
    ]
