# Generated by Django 6.0.5 on 2026-08-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_promobanner_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='promo_badge',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
