# Generated by Django 6.0.5 on 2026-08-26 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_medicine_promo_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='promobanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promo_banners/'),
        ),
    ]
