# Generated by Django 6.0.5 on 2026-08-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_promobanner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notif_delivery_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notif_doctor_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notif_lab_test_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notif_reminders',
            field=models.BooleanField(default=True),
        ),
    ]
