# Generated by Django 6.0.5 on 2026-08-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_user_notification_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderlog',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
