# Generated by Django 6.0.5 on 2026-08-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_reminderlog_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='follow_up_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
