# Generated by Django 6.0.5 on 2026-09-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_doctorappointment_follow_up_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notif_admin_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notif_admin_lab_bookings',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notif_admin_appointments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notif_admin_prescriptions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notif_admin_business',
            field=models.BooleanField(default=True),
        ),
    ]
