# Generated by Django 6.0.5 on 2026-09-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_user_admin_notif_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestbooking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('EN_ROUTE', 'Collector En Route'), ('ARRIVED', 'Collector Arrived'), ('SAMPLE_COLLECTED', 'Sample Collected'), ('SUBMITTED_TO_LAB', 'Submitted to Lab'), ('REPORT_READY', 'Report Ready'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
