# Generated by Django 6.0.5 on 2026-09-09 14:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_alter_labtestbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='included_tests',
            field=models.ManyToManyField(blank=True, related_name='included_in_packages', to='api.labtest'),
        ),
        migrations.CreateModel(
            name='LabBookingGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('KHALTI', 'Khalti'), ('ESEWA', 'eSewa'), ('CASH_ON_DELIVERY', 'Cash on Collection')], max_length=20, null=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('khalti_pidx', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('esewa_transaction_uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_booking_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lab_booking_groups',
                'ordering': ['-booked_at'],
            },
        ),
        migrations.AddField(
            model_name='labtestbooking',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='api.labbookinggroup'),
        ),
    ]
