# Generated by Django 6.0.5 on 2026-09-10 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_labtest_included_tests_labbookinggroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='pharmacy_rx_reject_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pharmacy_rx_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pharmacy_rx_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pharmacy_rx_status',
            field=models.CharField(blank=True, choices=[('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='', max_length=20),
        ),
    ]
