# Generated by Django 6.0.5 on 2026-09-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_orderitem_pharmacy_rx_reject_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestbooking',
            name='patient_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestbooking',
            name='patient_gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='labtestbooking',
            name='patient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labtestbooking',
            name='patient_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
