# Generated by Django 6.0.5 on 2026-09-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_address_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='reminder_1h_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='reminder_24h_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
