# Generated by Django 6.0.5 on 2026-09-18 11:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_doctor_profile_self_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='Swasthaya Team', max_length=255),
        ),
        migrations.AlterField(
            model_name='prescriptionlabtestitem',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_items', to='api.labtestbooking'),
        ),
        migrations.CreateModel(
            name='LabReportShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_shares', to='api.labtestbooking')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_lab_reports', to='api.doctor')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lab_report_shares',
                'ordering': ['-shared_at'],
                'unique_together': {('booking', 'doctor')},
            },
        ),
    ]
