# Generated by Django 6.0.5 on 2026-09-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_clear_dead_meeting_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='esewa_transaction_uuid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
