# Generated by Django 6.0.5 on 2026-09-25 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_half_step_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='follow_up_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='api.doctorappointment'),
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='is_follow_up_free',
            field=models.BooleanField(default=False),
        ),
    ]
