# Generated by Django 6.0.5 on 2026-09-27 11:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_seed_follow_up_free_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDateAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('slot_duration_minutes', models.PositiveIntegerField(default=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_availability', to='api.doctor')),
            ],
            options={
                'db_table': 'doctor_date_availability',
                'ordering': ['date'],
                'unique_together': {('doctor', 'date')},
            },
        ),
    ]
